version: 2.1

orbs:
    semver-orb: tv2norge/semver-orb@0.0.1

parameters:
    jdk-image:
      type: string
      default: "cimg/openjdk"  
    jdk-imagetag:
      type: string
      default: "11.0"
    workingdir:
      type: string
      default: "~/project"
    maven-build-cmd:
      type: string
      default: "clean install"
    s3-artifacts-store:
      type: string
      default: "dpr-demo-development-20220916083016121000000001"
    aws-region:
      type: string
      default: "eu-west-2"        

commands:
  verify: 
    description: "verify Commands"
    parameters:
        s3-artifact-store:
          type: string
          default: "none"
    steps:
      - run: 
          name: sync-artifacts
          command: |
            echo "S3 Bucket Evaluated Correct: << parameters.s3-artifact-store >>"          
  artifacts-sync:
    description: "Deploy Artifacts to S3"
    parameters:
      s3-artifact-store:
        type: string
        default: "none"           
    steps:
      - run: 
          name: sync-artifacts
          command: |
            echo s3://<< parameters.s3-artifact-store >>
            aws s3 sync target s3://<< parameters.s3-artifact-store >>/artifacts/cloud-platform/$CIRCLE_PROJECT_REPONAME/ --exclude "*" --include "digital-prisons-reporting/cloud-platform/target/cloud-platform*.jar" --region << pipeline.parameters.aws-region >>         
#           aws s3 sync target s3://<< parameters.s3-artifact-store >>/artifacts/domain-platform/$CIRCLE_PROJECT_REPONAME/ --exclude "*" --include "digital-prisons-reporting/domain-platform/target/domain-platform*.jar" --region << pipeline.parameters.aws-region >>         
            
jobs:
  version:
    parameters:
        artifact-store:
          type: string
          default: "none"       
    executor: semver-orb/default
    steps:
      - semver-orb/setup
      - semver-orb/print
    #  - semver-orb/tagnext
      - semver-orb/print
      - run: 
          name: Verify Release Version
          command: |
            echo "version checks: "; echo $SEMVER_VERSION; echo SEMVER="$SEMVER_VERSION" >> "${BASH_ENV}"
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - bash.env
      - verify:
          s3-artifact-store: << parameters.artifact-store >>           

  checkout:
    working_directory: << pipeline.parameters.workingdir >>  
    docker:
      - image: << pipeline.parameters.jdk-image >>:<< pipeline.parameters.jdk-imagetag >>     
    steps:
      - checkout          
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>  
      - run: |
          cat bash.env > $BASH_ENV      
      - run:
          name: Check Java Version
          command: |
            java --version;
            echo "Printing SEM VERSION"
            echo $SEMVER
            echo $CIRCLE_PROJECT_REPONAME
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - .

  tests:
    docker:
      - image: << pipeline.parameters.jdk-image >>:<< pipeline.parameters.jdk-imagetag >>
    steps:
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>
      - run:
          name: maven tests
          command: |
            mvn test            

  build:
    docker:
      - image: << pipeline.parameters.jdk-image >>:<< pipeline.parameters.jdk-imagetag >>
    steps:
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>
      - run: |
          cat bash.env > $BASH_ENV
      - run:
          name: set release version
          command: |
            find . -type f -name "*.xml" -exec sed -i "s/version_place_holder/$SEMVER/g" {} \;                 
      - run: 
          name: pre-build
          command: |
            mvn -N clean install;
            cd digital-prisons-reporting; mvn -N clean install
      - run: 
          name: build-common
          command: |
            cd digital-prisons-reporting/common; mvn clean install                 
      - run: 
          name: build-cloud-platform
          command: |
            cd digital-prisons-reporting/cloud-platform; mvn clean install
      - store_artifacts:
          path: digital-prisons-reporting/*/target/surefire-reports
          destination: surefire-reports           
          when: always
      - store_test_results:
          path: digital-prisons-reporting/*/target/surefire-reports
          when: always                                      
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - .

  deploy:
    parameters:
        artifact-store:
          type: string
          default: "none"      
    machine:
      enabled: true    
    steps:
      - when:
          condition:
            equal: [ DPR-100-HW, << pipeline.git.branch >> ]
          steps:          
            - run:
                name: notification
                command: echo "Deploy Artifacts to DEV"
      - when:
          condition:
            equal: [ DPR-100-HW, << pipeline.git.branch >> ]  
          steps:
            - attach_workspace:
                at: << pipeline.parameters.workingdir >>
            - run:
                name: listfiles
                command: |
                  pwd; ls -lsrt; ls -lsrt digital-prisons-reporting/cloud-platform/target/cloud-platform*.jar; ls -lsrt digital-prisons-reporting/cloud-platform/target    
            - artifacts-sync:
                s3-artifact-store: << parameters.artifact-store >>

  release:
    machine:
      enabled: true    
    steps:
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>        
      - run: 
          name: notification
          command: echo "Release Artifacts, if the branch is RELEASE"
      - run:
          name: Release
          command: |
            aws s3 sync target s3://<< pipeline.parameters.s3-artifacts-store >>/artifacts --exclude "*" --include "hello-world*.jar" --region << pipeline.parameters.aws-region >>

workflows:
  version: 2
  build:
    jobs:
      - version:
          name: "version"
          artifact-store: dpr-demo-development-20220916083016121000000001
      - checkout:
          name: "checkout"
          requires:
            - version          
#      - tests:
#          requires:
#            - checkout             
      - build:
          context:
            - digital-prison-reporting-dev
          requires:
            - checkout
      - deploy:
          context:
            - digital-prison-reporting-dev
          artifact-store: dpr-demo-development-20220916083016121000000001
          requires:
            - build
          filters:
            branches:
              only:
                - release            
      - release:
          context:
            - digital-prison-reporting-release
          requires:
            - build
            - deploy
          filters:
            branches:
              only:
                - release