version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout

  maven-build:
    docker:
        - image: cimg/openjdk:16.0
    steps:
      - run:
          name: Run tests
          command: mvn test        
      - run:
          name: Build
          command: mvn clean install

workflows:
  build:
    jobs:
    - checkout:
        filters:
            tags:
            ignore: /.*/
    - maven-build:
        requires:
            - checkout
        filters:
            branches:
            only:
                - main         